[workspace]
members = [
    "seria-config-core",
    "seria-config-service",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[workspace.dependencies]
csv = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-normalization = "0.1"
